# --- MAVEN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
# 500k for 3s5z_vs_3s6z, 6h_vs_8z, otherwise 50k
# 50,000 for matrix game, predator and prey || 700,000 for pursuit, lift and tiger
epsilon_anneal_time: 50000

runner: "maven"
batch_size_run: 1

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "maven_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
skip_connections: False
hyper_initialization_nonzeros: 0

agent: "maven_agent"
mac: "maven_mac"
noise_dim: 16    # 16 for both SMAC and matrix game

mi_loss: 0.001      # 0.001 for SMAC and 1 for matrix game

discrim_size: 64
discrim_layers: 1
mi_intrinsic: False
mi_scaler: 0.1
hard_qs: False

bandit_epsilon: 0.1
bandit_iters: 8
bandit_batch: 64
bandit_buffer: 512
bandit_reward_scaling: 20
bandit_use_state: True
bandit_policy: True

noise_bandit: True
noise_embedding_dim: 32
noise_bandit_lr: 0.1
noise_bandit_epsilon: 0.2
entropy_scaling: 0.001

name: "maven_bandit_5"